{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "versitygw.credentialsSecretName" . }}
  labels:
    {{- include "versitygw.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootAccessKeyId: {{ required "auth.accessKey is required when auth.existingSecret is not set" .Values.auth.accessKey | quote }}
  rootSecretAccessKey: {{ required "auth.secretKey is required when auth.existingSecret is not set" .Values.auth.secretKey | quote }}
{{- end }}
