FROM golang:latest

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY ./ ./
COPY ./tests/certs/* /etc/pki/tls/certs/

ARG IAM_DIR=/tmp/vgw
ARG SETUP_DIR=/tmp/vgw

RUN mkdir -p $IAM_DIR
RUN mkdir -p $SETUP_DIR

RUN go get github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon
