name: docker bats tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          mv tests/.env.docker.default tests/.env.docker
          mv tests/.secrets.default tests/.secrets
          docker build --build-arg="GO_LIBRARY=go1.21.7.linux-amd64.tar.gz" \
            --build-arg="AWS_CLI=awscli-exe-linux-x86_64.zip" --build-arg="MC_FOLDER=linux-amd64" \
            --progress=plain -f Dockerfile_test_bats -t bats_test .

      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Run Docker Container
        run: docker-compose -f docker-compose-bats.yml up posix_backend
