name: website hosting tests
permissions: {}
on: pull_request

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: run website hosting tests
        run: make test-website-hosting
